SESSION_INTERFACE_NAME = "org.voria.SamsungTools.Session"
SESSION_OBJECT_PATH_WEBCAM = "/Webcam"

SYSTEM_INTERFACE_NAME = "org.voria.SamsungTools.System"
SYSTEM_OBJECT_PATH_GENERAL = "/"
SYSTEM_OBJECT_PATH_BLUETOOTH = "/Bluetooth"
SYSTEM_OBJECT_PATH_WEBCAM = "/Webcam"
SYSTEM_OBJECT_PATH_WIRELESS = "/Wireless"
