#!/bin/bash

case ${1} in
	resume|thaw)
		dbus-send --system --print-reply --dest='org.voria.SamsungTools.System' '/' org.voria.SamsungTools.System.RestoreDevicesLastStatus > /dev/null
		;;
esac

exit 0